# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7521e37f88e252845c0fb50c7002a531a4fa8500d1dd53d575b2f793c0fc2c95c6bcded7d8e8df1bcd7a43fec28c74c5f9a457c3fe36908c02ca8895bb41368

test:
  secret_key_base: b6cb17204fbe5fd5389aa7a84f64699c0d9f116406221f48e9d2d1d43a1d4fd8c892e67a686eecef1ec41a101decb8f64f8f1e7529330d6d508b16399da52cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
